# Generated by Django 4.1.2 on 2022-11-30 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('k', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.IntegerField(default=0)),
                ('cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Morbidity',
            fields=[
                ('morbidityid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('datediagnosed', models.DateTimeField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('morbidities', models.ManyToManyField(to='Kidney.morbidity')),
            ],
        ),
        migrations.CreateModel(
            name='LabVitals',
            fields=[
                ('vitalid', models.BigAutoField(primary_key=True, serialize=False)),
                ('K', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Phos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Na', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Creatinine', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Albumin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BloodSugar', models.IntegerField(default=0)),
                ('BloodPressure', models.CharField(max_length=10)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('personid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kidney.person')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entryid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('notes', models.CharField(max_length=3000)),
                ('status', models.CharField(max_length=25)),
                ('personid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kidney.person')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('foodentryid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('mealType', models.CharField(max_length=20)),
                ('foods', models.ManyToManyField(to='Kidney.food')),
                ('personid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kidney.person')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('exerciseid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.today)),
                ('personid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kidney.person')),
            ],
        ),
    ]
