# Generated by Django 4.1.2 on 2022-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kidney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseentry',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseentry',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
