# Generated by Django 4.1.2 on 2022-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kidney', '0002_exerciseentry_duration_exerciseentry_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
