# Generated by Django 4.1.2 on 2022-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kidney', '0003_alter_foodentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseentry',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='labvitals',
            name='Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='morbidity',
            name='datediagnosed',
            field=models.DateField(blank=True),
        ),
    ]
